# Needs to be triggered manually
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  job_1:
    name: "Show Terraform Destroy Plan"
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      # Authenticate to google cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      # Setup google cloud SDK
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
      # Show destroy plan
      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: false
  
  job_2:
    name: "Run Terraform Destroy"
    needs: job_1
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      # Authenticate to google cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      # Setup google cloud SDK
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
      # Run Terraform Destroy
      - name: Destroy resources jobs
        id: destroy
        run: terraform destroy -auto-approve
